# Generated by Django 4.1.3 on 2022-11-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_message_is_readen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_readen',
            field=models.BooleanField(default=False, verbose_name='Сообщение прочитано'),
        ),
    ]
